# Generated by Django 4.2 on 2023-04-28 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
