# Generated by Django 4.2 on 2023-04-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
