# Generated by Django 4.2 on 2023-04-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
