# Generated by Django 4.2 on 2023-04-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
    ]
