# Generated by Django 4.2 on 2023-04-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
