# Generated by Django 4.2 on 2023-04-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="itmes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "Items_List",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Main_User",
        ),
    ]
